export const REPOSITORY_LOV = Symbol("REPOSITORY_LOV")
export const REPOSITORY_ACCOUNT = Symbol("REPOSITORY_ACCOUNT")
export const REPOSITORY_LOCATION = Symbol("REPOSITORY_LOCATION")
export const REPOSITORY_ROLE = Symbol("REPOSITORY_ROLE")